apiVersion: v1
kind: Pod
metadata:
  name: worker-app-pod
  labels:
    name: worker-app-pod
    app: demo-voting-app
spec:
  containers:
  - image: kodekloud/examplevotingapp_worker:v1
    name: worker-app-container
