# kubectl kustomize . > full-stack-local.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment-db.yaml
  - deployment-redis.yaml
  - deployment-result-app.yaml
  - deployment-voting-app.yaml
  - service-db.yaml
  - service-redis.yaml
  - service-result-app.yaml
  - service-voting-app.yaml
  - deployment-worker-app.yaml
