apiVersion: v1
kind: Pod
metadata:
  name: db-pod
  labels:
    name: db-pod
    app: demo-voting-app
spec:
  containers:
  - image: postgres
    name: db-container
    ports:
      - containerPort: 5432
    env:
      - name: POSTGRES_USER
        value: postgres
      - name: POSTGRES_PASSWORD
        value: postgres
