version: "3"

services:
  vote:
    build: ./vote
    depends_on:
      - "redis"
    ports:
      - "5000:80"
    networks:
      - front-tier
      - back-tier

  result:
    build: ./result
    depends_on:
      - "db"
    ports:
      - "5001:80"
    networks:
      - front-tier
      - back-tier

  worker:
    build: ./worker
    depends_on:
      - "redis"
      - "db"
    networks:
      - back-tier

  redis:
    image: redis:5.0-alpine3.10
    networks:
      - back-tier

  db:
    image: postgres:9.4
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    networks:
      - back-tier

networks:
  front-tier:
  back-tier: