apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    name: db-deployment
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: db-pod
      app: demo-voting-app
  template:
    metadata:
      name: db-pod
      labels:
        name: db-pod
        app: demo-voting-app
    spec:
      containers:
      - image: postgres
        name: db-container
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: postgres